apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-czzo
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-czzo
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-czzo
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-czzo
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-czzo
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-wvzq-tenant/rhtap-demo-app/hacbs-test-project-czzo@sha256:3f93fce9122eb3ba8ea620afdeb25ed848bad4386900ca3e22700f98c68f7fae
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
